function loadAndRun(hCS, executableFile, varargin)
% LOADANDRUN Deploy an application binary to the AM13E2X target via CCS scripting.
%
%   loadAndRun(hCS, executableFile)
%   loadAndRun(hCS, executableFile, ...)
%
%   Parameters:
%       hCS            - Active Simulink configuration set handle (currently
%                        unused; reserved for future target-specific config
%                        retrieval such as hardware board name or core arch).
%                        The active config set is re-fetched internally via
%                        getActiveConfigSet(bdroot).
%       executableFile - Full path to the compiled application binary (.out)
%                        generated by Simulink code generation.
%                        E.g. 'C:/work/model_ert_rtw/model.out'
%       varargin       - Reserved for future use. Currently unused.
%
%   Migration help from older DSS to new CCS scripting API:
%   https://downloads.ti.com/ccs/esd/documents/users_guide_ccs_20.4.0/ccs_debug-scripting-migration.html

%  Copyright (C) 2026 Texas Instruments Incorporated
%
%  Redistribution and use in source and binary forms, with or without
%  modification, are permitted provided that the following conditions
%  are met:
%
%    Redistributions of source code must retain the above copyright
%    notice, this list of conditions and the following disclaimer.
%
%    Redistributions in binary form must reproduce the above copyright
%    notice, this list of conditions and the following disclaimer in the
%    documentation and/or other materials provided with the
%    distribution.
%
%    Neither the name of Texas Instruments Incorporated nor the names of
%    its contributors may be used to endorse or promote products derived
%    from this software without specific prior written permission.
%
%  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
%  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
%  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
%  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
%  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
%  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
%  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
%  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
%  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
%  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
%  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


fprintf('Load and run triggered \n');
this_file_dir = mfilename('fullpath');
[this_dir, ~] = fileparts(this_file_dir);

% Get CCSROOT environment variable
ccsRoot = getenv('CCSROOT');
if isempty(ccsRoot)
    error('CCSROOT environment variable is not set, re-run the setup script');
end

% Get CCS scripting tool path E.g., C:\ti\ccs2050\ccs\scripting
ccsScriptingPath = fullfile(ccsRoot, 'ccs', 'scripting');
ccsScriptingTool = fullfile(ccsScriptingPath, 'run.bat');
ccsScriptingTool = strrep(ccsScriptingTool,'\', '/');
if ~isfile(ccsScriptingTool)
    error('CCS scripting tool not available, try re-installing CCS');
end

% MATLAB constructs and calls the following command:
%   run.bat <script.js> <ccsRoot> <ccxmlPath> <coreArch> <executableFile>
%
% Inside openSession.js, process.argv maps as:
%   args[0] = node executable        (managed internally by run.bat)
%   args[1] = launcher shim           (managed internally by run.bat)
%   args[2] = openSession.js path     (the script being executed)
%   args[3] = CCS root path           e.g. C:/ti/ccs2050
%   args[4] = ccxml file path         e.g. C:/.../AM13E2X.ccxml
%   args[5] = core architecture       e.g. CORTEX_M33
%   args[6] = application binary path e.g. C:/.../model.out
%
% E.g.: run.bat openSession.js 'C:/ti/ccs2050' 'C:/.../AM13E2X.ccxml' 'CORTEX_M33' 'model.out'

% args[2]: Get deployer javascript file path
deployerJS = fullfile(this_dir, 'openSession.js');
deployerJS = strrep(deployerJS,'\', '/');

% args[3]: ccsRoot (passed directly from getenv('CCSROOT'))

% args[4]: Get ccxml file path per TI hardware family
hwName = get_param(hCS, 'HardwareBoard');
ccxmlPath = fullfile(this_dir, [hwName '.ccxml']);
ccxmlPath = strrep(ccxmlPath,'\', '/');

% args[5]: Core architecture e.g. CORTEX_M33
coreArch = 'CORTEX_M33';

% args[6]: Application binary file e.g. model.out
executableFile = strrep(executableFile,'\', '/');
[path, name, ~] = fileparts(executableFile);
copyfile(executableFile, fullfile(path,[name '.elf']));

% run the script with needed arguments
% IMPORTANT: run.bat may spawn Node.js asynchronously and return before
% the flash operation completes. To guarantee synchronous execution,
% we wrap the call so MATLAB waits for the Node.js process to fully exit.
% This prevents the next slbuild iteration from starting a new CCS session
% while the previous one still holds the JTAG lock.
commandStr = [ccsScriptingTool ' ' deployerJS ' ' ccsRoot ' ' ccxmlPath ' ' coreArch ' ' executableFile];

% ROOT CAUSE FIX: Kill the orphaned XDS110 USB debug server.
% ds.shutdown() in openSession.js exits the Node.js process but leaves
% xds110_server.exe alive holding exclusive access to the JTAG/USB port.
% The next loadProgram() call deadlocks because two sessions compete for
% the same XDS110 connection — flash completes but response never arrives.
% xds110_server.exe is a child of the scripting session, NOT CCS IDE,
% so killing it does not affect any open CCS IDE instance.
fprintf('Releasing XDS110 server...\n');
system('taskkill /F /IM xds110_server.exe /T 2>nul');
% Also cover alternate process name used in some CCS versions
system('taskkill /F /IM xdsdfu.exe /T 2>nul');
pause(2);
fprintf('XDS110 server released.\n');

fprintf('Executing: %s\n', commandStr);
t_start = tic;

% system() with third arg ''-echo'' prints output live and waits for process exit
[status, result] = system(commandStr, '-echo');

t_elapsed = toc(t_start);
fprintf('CCS scripting completed in %.1f seconds with status %d\n', t_elapsed, status);

if isequal(status, 0)
    fprintf(result);
else
    error('Error running CCS scripting tool. Exit code: %d, Output: %s', status, result);
end

% Extra guard: if run.bat returned suspiciously fast (< 2s), the Node.js
% process is likely still running in background. Wait for it to finish.
if t_elapsed < 2.0
    fprintf('Warning: CCS scripting returned in %.1fs — may be async. Waiting for JTAG release...\n', t_elapsed);
    pause(8);
end
end
