function setup_am13x
% SETUP Add IAR Tools path to environment variables in a makefile

%  Copyright (C) 2025-2026 Texas Instruments Incorporated
%
%  Redistribution and use in source and binary forms, with or without
%  modification, are permitted provided that the following conditions
%  are met:
%
%    Redistributions of source code must retain the above copyright
%    notice, this list of conditions and the following disclaimer.
%
%    Redistributions in binary form must reproduce the above copyright
%    notice, this list of conditions and the following disclaimer in the
%    documentation and/or other materials provided with the
%    distribution.
%
%    Neither the name of Texas Instruments Incorporated nor the names of
%    its contributors may be used to endorse or promote products derived
%    from this software without specific prior written permission.
%
%  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
%  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
%  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
%  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
%  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
%  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
%  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
%  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
%  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
%  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
%  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

    tmp_Fullpath = mfilename('fullpath');
    [setupFileDir, ~] = fileparts(tmp_Fullpath);

    load(fullfile(setupFileDir, 'tool_install_paths_iar.mat'), "tool_install_path_iar");

    % IAR-specific makefile tokens
    makefileTokens(1).Name  = 'IARROOT';
    makefileTokens(1).Value = strrep(string(tool_install_path_iar(1)), '\','/');

    makefileTokens(2).Name  = 'IARARMINSTALLDIR';
    makefileTokens(2).Value = strrep(string(tool_install_path_iar(2)), '\','/');

    makefileTokens(3).Name  = 'MCUSDKINSTALLDIR';
    makefileTokens(3).Value = strrep(string(tool_install_path_iar(3)), '\','/');

    makefileTokens(4).Name  = 'LINKERCMDDIR';
    makefileTokens(4).Value = strrep(setupFileDir, '\','/');

    % Optional: IAR common tools path (for cspybat, etc.)
    makefileTokens(5).Name  = 'IARCOMMONDIR';
    makefileTokens(5).Value = strrep(string(fullfile(tool_install_path_iar(1), 'common', 'bin')), '\','/');

    createToolchainPathMakefile(makefileTokens);
end

function createToolchainPathMakefile(makefileTokens)
    % Creates mw_iar_arm_tools_path.mk with IAR toolchain paths
    fileName = 'mw_iar_arm_tools_path.mk';
    buildDir = pwd;
    [fid, errMsg] = fopen(fullfile(buildDir, fileName), 'w');
    if (isequal(fid, -1))
        error(message('codertarget:build:AssemblyFlagsFileError', fileName, errMsg));
    end
    fidCleanup = onCleanup(@() fclose(fid));

    % Write header comment
    fprintf(fid, '# IAR ARM Toolchain Paths\n');
    fprintf(fid, '# Auto-generated by setup_am13x.m for iar arm\n\n');

    for i = 1:numel(makefileTokens)
        if ispc
            rootDir = strrep(makefileTokens(i).Value, '\', '/');
        else
            rootDir = makefileTokens(i).Value;
        end
        fprintf(fid, '%s = %s\n', makefileTokens(i).Name, rootDir);
    end
end