function onAfterCodegenHook(hCS,buildInfo)
%ONAFTERCODEGENHOOK Creates an archive of Embeded Coder Generated Files
%
%This function generates an archive of all the Simulink generated files
%This file generates a bat file to create a library of Simulink generated C
%files. The Makefiles link command will be replaced by a call to the bat
%file gnerated here.

%  Copyright (C) 2026 Texas Instruments Incorporated
%
%  Redistribution and use in source and binary forms, with or without
%  modification, are permitted provided that the following conditions
%  are met:
%
%    Redistributions of source code must retain the above copyright
%    notice, this list of conditions and the following disclaimer.
%
%    Redistributions in binary form must reproduce the above copyright
%    notice, this list of conditions and the following disclaimer in the
%    documentation and/or other materials provided with the
%    distribution.
%
%    Neither the name of Texas Instruments Incorporated nor the names of
%    its contributors may be used to endorse or promote products derived
%    from this software without specific prior written permission.
%
%  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
%  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
%  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
%  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
%  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
%  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
%  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
%  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
%  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
%  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
%  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

% Generate SysConfig files if .syscfg file exists
try
    am13x.generateSyscfgFiles(hCS, buildInfo);
catch ME
    error(['SysConfig generation failed: %s. Set absolute SysConfig path by navigating to ' ...
        'Hardare Settings -> Hardware Implementation -> Target Hardware Resources -> Sysconfig -> Sysconfig Project File.  '], ME.message);
end

% Get the linker command directory from environment
linkerCmdDir = getenv('LINKERCMDDIR');

% Ensure proper path format with forward slashes
linkerCmdDir = strrep(linkerCmdDir, '\', '/');

toolchain = buildInfo.getBuildToolInfo('ToolchainInfo');
toolchainName = toolchain.Name;
isIARToolchain = contains(toolchainName, 'IAR', 'IgnoreCase', true);

if isIARToolchain
    % IAR uses .icf linker config files directly without -Wl prefix
    % The linker config is already specified in the toolchain with --config flag
    % so we don't add it again here to avoid duplicate --config flags
    buildInfo.addIncludePaths(fullfile(getenv('MCUSDK_INCLUDE'), 'compiler', 'm33_iar_arm'));
    % required for interrupt only case, OverrunFlag generated by ECoder periodic scheduler is
    % not used
    buildInfo.addCompileFlags({'--diag_suppress=Pe550', '--diag_suppress=Pe177'});
else
    % TI ARM Clang uses .cmd files with -Wl prefix
    linkerCmdFile = ['"', linkerCmdDir, '/linker_m33_ti_arm_clang.cmd"'];
    % Add linker flags with -Wl prefix for TI ARM Clang
    buildInfo.addLinkFlags(['-Wl,', linkerCmdFile]);
    buildInfo.addIncludePaths(fullfile(getenv('MCUSDK_INCLUDE'), 'compiler', 'm33_ti_arm_clang'));
    % required for interrupt only case, OverrunFlag generated by ECoder ECoder periodic scheduler is
    % not used
    buildInfo.addCompileFlags('-Wno-unused-variable');
end

% Add include paths
buildInfo.addIncludePaths(getenv('TMU_INCLUDE'));
buildInfo.addIncludePaths(getenv('CMSISDSP_INCLUDE'));
buildInfo.addIncludePaths(getenv('CMSISCORE_INCLUDE'));
buildInfo.addIncludePaths(getenv('HAL_INCLUDE'));
buildInfo.addIncludePaths(getenv('HALCFG_INCLUDE'));



% Add defines
baudRate = getpref('AM13xPILpref', 'Baud');
addDefines(buildInfo,  ['-DAM13x_BAUDRATE=' baudRate], 'SkipForSil');
% Since we are use semihosting (libsysbm.a)
addDefines(buildInfo, '-D_DLIB_FILE_DESCRIPTOR', 'SkipForSil');


% Create CCS project only for normal target builds with TI ARM Clang toolchain.
% Skip for:
%   PIL      : TargetApplicationFramework / pil_main_am13x
%   Ext Mode : XCP serial transport, no standalone CCS project needed
%   IAR      : IAR toolchain uses IAR Embedded Workbench, not CCS
isExternalMode = false;

% Skip if using IAR toolchain (CCS is TI-specific)
if isIARToolchain
    skipCCSProject = true;
else
    % Check for PIL or External Mode
    try
        simMode        = get_param(buildInfo.getBuildName, 'SimulationMode');
        isExternalMode = strcmpi(simMode, 'external');
        skipCCSProject = strcmpi(simMode, 'processor-in-the-loop (pil)') || ...
            isExternalMode;
    catch
        % Model may not be loaded in sub-builds - fall back to path check
        % PIL sub-build directories always contain [filesep 'pil' filesep]
        try
            buildDir       = RTW.getBuildDir(buildInfo.getBuildName);
            skipCCSProject = contains(buildDir.BuildDirectory, ...
                [filesep 'pil' filesep], 'IgnoreCase', true);
        catch
            skipCCSProject = false;
        end
    end
end

% External mode requires Debug build configuration to generate DWARF debug
% symbols. Without them the XCP server cannot resolve variable addresses at
% runtime. Fail early with a clear message rather than producing a silent
% mis-build.
if isExternalMode
    validateExternalModeBuildConfig(hCS, buildInfo);
end

if ~skipCCSProject
    am13x.createCCSproject(hCS, buildInfo);
end
end

%% -----------------------------------------------------------------------
function validateExternalModeBuildConfig(hCS, buildInfo)
% VALIDATEEXTERNALMODEBUILDCONFIG  Enforce Debug build for External mode.
%
% External mode uses XCP over serial to tune parameters and log signals on
% the running target. The XCP server resolves variable addresses by reading
% DWARF debug symbols from the ELF. Only the 'Debug' build configuration
% emits full DWARF information; 'Faster builds' and 'Faster runs' omit or
% strip debug symbols, so the connection would fail silently at runtime.

REQUIRED_CONFIG = 'Debug';

% Read the active build configuration from the model
try
    buildConfig = get_param(hCS.getModel, 'BuildConfiguration');
catch
    % If the model handle is not accessible fall back to buildInfo name
    try
        buildConfig = get_param(buildInfo.getBuildName, 'BuildConfiguration');
    catch ME
        warning(ME.identifier, ...
            'Could not verify BuildConfiguration for External mode: %s', ME.message);
        return;
    end
end

if ~strcmpi(buildConfig, REQUIRED_CONFIG)
    error('am13x:externalMode:wrongBuildConfig', ...
        ['External mode requires the ''%s'' build configuration because ' ...
        'XCP uses DWARF debug symbols to resolve variable addresses on ' ...
        'the target.\n' ...
        'Current configuration: ''%s''\n' ...
        'Change it in: Configuration Parameters > Code Generation > ' ...
        'Build configuration, then rebuild.'], ...
        REQUIRED_CONFIG, buildConfig);
end
end
